env: "local" # local, dev, prod
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8082"
postgres_db:
  user: "postgres"
  dbname: "postgres"
  password: "1233"
  host: "localhost"
  port: "5432"
  sslmode: "disable"